### ISSUE TITLE
Grin-Pool User Interface

### ISSUE THREAD

**Issue by xwen01** [grin-pool/grin-pool#42]
I followed instructions to setup Grin-Pool User Interface. Under grin-pool/grin-py/webui-js, "yarn" command worked, but "yarn start" got error:

yarn run v1.12.3
warning package.json: No license field
$ node scripts/start.js
module.js:550
    throw err;
    ^

Error: Cannot find module '../config/env'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ray/grin-pool/grin-py/webui-js/scripts/start.js:15:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Any advice? Thanks!

**Comment by saydulk** [comment]
![Screenshot from 2019-05-25 03-43-15](https://user-images.githubusercontent.com/1058663/58358097-3f651600-7e9f-11e9-9241-925f316ddc08.png)
same here
