### ISSUE TITLE
Can't use email as username in python script

### ISSUE THREAD

**Issue by gagarin55** [grin-pool/grin-pool#51]
Subj

```
$ python MWGP_payout.py 
 
############# MWGrinPool Payout Request Script #############
## Started: 2019-01-24 09:30:10.138945 
## 
   MWGrinPool Username: h.h@gmail.com
Traceback (most recent call last):
  File "MWGP_payout.py", line 49, in <module>
    username = input("   MWGrinPool Username: ")
  File "<string>", line 1
    h.h@gmail.com
               ^
SyntaxError: invalid syntax
```

**Comment by bladedoyle** [comment]
The payout script requires python3.   The error you show above is a result of using python2
